version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_DASHBOARD_APP_API_URL: http://localhost:8080/api/v1/dashboards
      VITE_DASHBOARD_APP_WEBSOCKET_URL: http://localhost:8080/api/v1/ws
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      FRONTEND_URL: http://localhost:5173
      DB_URL: jdbc:mysql://db:3306/vehicle_dashboard?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vehicle_dashboard
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
